from docker.elastic.co/logstash/logstash:8.1.0

run curl \
  -o /usr/share/logstash/logstash-core/lib/jars/mssql-jdbc-10.2.0.jre11.jar \
  https://github.com/microsoft/mssql-jdbc/releases/download/v10.2.0/mssql-jdbc-10.2.0.jre11.jar
